# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=2)),
                ('score', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Match',
            new_name='TFMatch',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='TFTeam',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AlterField(
            model_name='tfteam',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='tf.TFPlayer'),
        ),
        migrations.AlterField(
            model_name='tfteam',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='tf.TFPlayer'),
        ),
    ]
