# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0003_auto_20151230_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TF_Match',
            new_name='TfMatch',
        ),
        migrations.RenameModel(
            old_name='TF_Player',
            new_name='TfPlayer',
        ),
        migrations.RenameModel(
            old_name='TF_Team',
            new_name='TfTeam',
        ),
    ]
