# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0006_auto_20151231_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfplayer',
            old_name='score',
            new_name='player_elo',
        ),
        migrations.AddField(
            model_name='tfteam',
            name='team_elo',
            field=models.IntegerField(default=0),
        ),
    ]
