# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0008_tfteam_is_single_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfplayer',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
