# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0009_tfplayer_matches_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfteam',
            name='team_matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
