# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0010_tfteam_team_matches_won'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tfmatch',
            options={'verbose_name_plural': 'tf matches'},
        ),
        migrations.AddField(
            model_name='tfmatch',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tfplayer',
            name='player_elo',
            field=models.IntegerField(default=1000),
        ),
    ]
