# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-03 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0012_remove_tfteam_team_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfteam',
            name='players',
            field=models.ManyToManyField(to='tf.TfPlayer'),
        ),
    ]
