# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0017_migrate_team1_team2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfmatch',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='tfmatch',
            name='score2',
        ),
        migrations.RemoveField(
            model_name='tfmatch',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='tfmatch',
            name='team2',
        ),
    ]
