# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0020_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_elo',
            new_name='tf_player_elo',
        ),
    ]
