# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0022_auto_20160723_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tf_last_played',
            field=models.DateTimeField(null=True),
        ),
    ]
