# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0024_remove_tfmatch_invisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fifa_last_played',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_player_elo',
            field=models.IntegerField(default=1000),
        ),
    ]
