# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0025_auto_20160724_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfteam',
            old_name='team_matches_played',
            new_name='tf_team_matches_played',
        ),
        migrations.RenameField(
            model_name='tfteam',
            old_name='team_matches_won',
            new_name='tf_team_matches_won',
        ),
    ]
