# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0026_auto_20160724_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TfTeam',
            new_name='Team',
        ),
    ]
