# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0027_auto_20160724_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fifa_team_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='fifa_team_matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
