# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0028_auto_20160724_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifaMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.CharField(default='0 0', max_length=5)),
                ('played_date', models.DateTimeField(verbose_name='date played')),
                ('teams', models.ManyToManyField(to='tf.Team')),
            ],
            options={
                'verbose_name_plural': 'fifa matches',
            },
        ),
    ]
