# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0029_fifamatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfmatch',
            name='elo_changes',
            field=models.CharField(default='0 0', max_length=9),
        ),
        migrations.AddField(
            model_name='tfmatch',
            name='elos',
            field=models.CharField(default='0 0', max_length=9),
        ),
    ]
