# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0030_auto_20160729_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_date', models.DateTimeField(verbose_name='date played')),
                ('scores', models.CharField(default='0 0', max_length=5)),
                ('elos', models.CharField(default='0 0', max_length=9)),
                ('elo_changes', models.CharField(default='0 0', max_length=9)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='TfMatch_new',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tf.Match')),
            ],
            options={
                'verbose_name_plural': 'tf matches',
            },
            bases=('tf.match',),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='tf.Team'),
        ),
    ]
