# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 18:26
from __future__ import unicode_literals

from django.db import migrations

def migrate_tfmatches(apps, schema_editor):
    TfMatch_old = apps.get_model("tf", "TfMatch")
    TfMatch_new = apps.get_model("tf", "TfMatch_new")
    for m_old in TfMatch_old.objects.all():
        m_new = TfMatch_new()
        m_new.played_date = m_old.played_date
        m_new.scores = m_old.scores
        m_new.elos = m_old.elos
        m_new.elo_changes = m_old.elo_changes
        m_new.save()
        for id in [t.id for t in m_old.teams.all()]:
            m_new.teams.add(id)
        m_new.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0031_auto_20160731_1917'),
    ]

    operations = [
        migrations.RunPython(migrate_tfmatches),
    ]
