# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0033_auto_20160731_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TfMatch_new',
            new_name='TfMatch',
        ),
    ]
