# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 20:50
from __future__ import unicode_literals

from django.db import migrations

def migrate_fifamatches(apps, schema_editor):
    FifaMatch_old = apps.get_model("tf", "FifaMatch_old")
    FifaMatch_new = apps.get_model("tf", "FifaMatch")
    for m_old in FifaMatch_old.objects.all():
        m_new = FifaMatch_new()
        m_new.played_date = m_old.played_date
        m_new.scores = m_old.scores
        m_new.save()
        for id in [t.id for t in m_old.teams.all()]:
            m_new.teams.add(id)
        m_new.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0036_fifamatch'),
    ]

    operations = [
        migrations.RunPython(migrate_fifamatches),
    ]
