# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0037_migrate_fifamatches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fifamatch_old',
            name='teams',
        ),
        migrations.DeleteModel(
            name='FifaMatch_old',
        ),
    ]
