# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0039_auto_20160731_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.IntegerField(default=0),
        ),
    ]
