# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0041_auto_20160803_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fifamatch',
            name='matchtype',
        ),
        migrations.RemoveField(
            model_name='tfmatch',
            name='matchtype',
        ),
        migrations.AddField(
            model_name='match',
            name='matchtype',
            field=models.CharField(default='NA', max_length=2),
        ),
    ]
